version: '2'
services:
    go:
        image: golang:1.8-alpine
        ports:
            - "80:8080"
        volumes:
           - ./:/go/src/recipes
        links:
            - postgres
            - mongodb
            - redis
        environment:
            DEBUG: 'true'
            PORT: '8080'
            DB_PASSWORD: 'ksavinash9'
            DB_USER: 'ksavinash9'
            DB_NAME: 'ksavinash9'
            DB_PORT: '5432'
            DB_HOST: 'postgres'
            LOG_LEVEL: 'info'
            MAX_PREP_TIME_IN_MINS: '180'
        entrypoint:
            - /go/src/recipes/alpine-entrypoint.sh

    postgres:
        image: onjin/alpine-postgres:9.5
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: ksavinash9
            POSTGRES_PASSWORD: ksavinash9
            POSTGRES_DB: ksavinash9

    mongodb:
        image: mvertes/alpine-mongo:3.2.3
        restart: unless-stopped
        ports:
            - "27017:27017"

    redis:
        image: sickp/alpine-redis:3.2.2
        restart: unless-stopped
        ports:
            - "6379:6379"
